# Generated by Django 4.1.3 on 2022-11-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='book',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='bookaudio',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='cover',
            field=models.ImageField(upload_to='media'),
        ),
    ]
