# Generated by Django 4.1.3 on 2022-11-16 05:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0003_alter_ebook_book_alter_ebook_bookaudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
