# Generated by Django 4.1.3 on 2022-11-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0005_userebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userebook',
            name='book',
            field=models.FileField(upload_to='usermedia'),
        ),
        migrations.AlterField(
            model_name='userebook',
            name='bookaudio',
            field=models.FileField(upload_to='usermedia'),
        ),
        migrations.AlterField(
            model_name='userebook',
            name='cover',
            field=models.ImageField(upload_to='usermedia'),
        ),
    ]
