# Generated by Django 4.1.3 on 2022-11-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0010_alter_userebook_book_alter_userebook_bookaudio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userebook',
            name='book',
            field=models.FileField(upload_to='usermedia/'),
        ),
        migrations.AlterField(
            model_name='userebook',
            name='bookaudio',
            field=models.FileField(upload_to='usermedia/'),
        ),
        migrations.AlterField(
            model_name='userebook',
            name='cover',
            field=models.ImageField(upload_to='usermedia/'),
        ),
    ]
