# Generated by Django 4.1.3 on 2022-11-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0012_alter_userebook_book_alter_userebook_bookaudio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfToMp3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.FileField(upload_to='audio')),
            ],
        ),
    ]
