# Generated by Django 4.1.3 on 2022-11-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0013_pdftomp3'),
    ]

    operations = [
        migrations.CreateModel(
            name='audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiobook', models.FileField(upload_to='audio')),
            ],
        ),
    ]
