# Generated by Django 4.1.3 on 2022-11-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0014_audiobook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='audiobook',
        ),
    ]
