# Generated by Django 4.1.3 on 2022-11-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0016_order_delete_ebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
