# Generated by Django 4.1.3 on 2022-11-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0017_remove_order_price_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
