# Generated by Django 4.1.3 on 2022-11-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0018_order_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
